alias g='git'
alias v='nvim'
alias e='exit'
alias l='ls -AlFh | sort -r'

alias u="brew update && brew upgrade --greedy && brew autoremove && brew cleanup --prune=all"
alias uz='v $HOME/.zshrc && . $HOME/.zshrc'
alias ua='v $DOT_FILES/zsh/aliases.zsh && . $HOME/.zshrc'

alias cd.='cd $DOT_FILES'
alias cdp='cd $PROJECTS'
alias cdr='cd $DRIVENBRANDS/commerce-cloud'
alias cdh='cd $DRIVENBRANDS/hybris/hybris/bin/platform'
alias ...........='cd ../../../../../../../../../..'
alias ..........='cd ../../../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ........='cd ../../../../../../..'
alias .......='cd ../../../../../..'
alias ......='cd ../../../../..'
alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'

alias hd='./hybrisserver.sh debug'
alias hs='./hybrisserver.sh start'
alias hp='./hybrisserver.sh stop'

alias a='ant'
alias aa='ant all'
alias aca='ant clean all'
alias au='ant updatesystem'
alias aui='ant mpstorefront_compileuisrc'

alias d='docker'
alias dc='d ps -a --format "table {{.Names}}\\t{{.Status}}\\t{{.Image}}"'
alias di='d image list --format "table {{.Repository}}\\t{{.Tag}}"'
alias ds='d start'
alias dp='d stop'
alias de='d exec -itu root'
alias dip='d image prune -f'
