# aliases
alias g='git'
alias v='nvim'
alias e='exit'
alias l='ls -AlFh'
alias dl='dirs -v'
alias off='shutdown -P now'
for index ({1..9}) alias "$index"="cd +${index}"; unset index
# modify
alias u='sudo dnf up -yq && sudo dnf autoremove -yq && ug'
alias ug='. $DOT_FILES/grub.sh'
alias uz='v $HOME/.zshrc && source $HOME/.zshrc'
alias ua='v $DOT_FILES/zsh/aliases.zsh && source $HOME/.zshrc'
alias ui='v $DOT_FILES/init.lua'
# directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ..........='cd ../../../../../../../../..'
alias ...........='cd ../../../../../../../../../..'
alias cd.='cd $DOT_FILES'
alias cdp='cd $HOME/Projects'
alias cdh='cd $HYBRIS_PLATFORM'
# hybris
alias hs='./hybrisserver.sh start'
alias hp='./hybrisserver.sh stop'
alias hd='./hybrisserver.sh debug'
# ant
alias a='ant'
alias aa='a all'
alias aca='a clean all'
alias ab='a build'
alias acb='a clean build'
alias ai='a initialize'
alias au='a updatesystem'
alias ac='a runcronjob'
alias ay='a yunitinit'
alias aat='a alltests'
alias aut='a unittests'
alias ait='a integrationtests'
# virtualbox
alias vml='VBoxManage list vms'
alias vms='VBoxManage startvm d3c95e44-05dc-40b2-9efa-7e30b67c4387 --type headless'
alias vmp='VBoxManage controlvm d3c95e44-05dc-40b2-9efa-7e30b67c4387 poweroff'
# sqldeveloper
alias sql='sqldeveloper&!'
# docker
alias d='docker'
alias ds='d ps -a --format "table {{.Names}}\\t{{.Status}}\\t{{.Image}}"'
alias di='d image list --format "table {{.Repository}}\\t{{.Tag}}"'
alias dr='d run -itd --name'
alias db='d build -t $1 .'
alias dst='d start'
alias de='d exec -it $1 /bin/bash'
alias drm='d rm -f'
alias drmi='d rmi -f'
alias dsp='d system prune'
# compose
alias dc='d compose'
alias dcu='dc up'
alias dcb='dc build'
# aws-cli
alias aws='d run --rm -ti -v ~/.aws:/root/.aws -v $(pwd):/aws amazon/aws-cli'
